/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ProjectsLazyImport = createFileRoute('/projects')()
const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const ProjectsLazyRoute = ProjectsLazyImport.update({
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/about': typeof AboutLazyRoute
  '/projects': typeof ProjectsLazyRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutLazyRoute
  '/projects': typeof ProjectsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/about': typeof AboutLazyRoute
  '/projects': typeof ProjectsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/projects'
  id: '__root__' | '/about' | '/projects'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutLazyRoute: typeof AboutLazyRoute
  ProjectsLazyRoute: typeof ProjectsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AboutLazyRoute: AboutLazyRoute,
  ProjectsLazyRoute: ProjectsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/projects"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/projects": {
      "filePath": "projects.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
